### ISSUE TITLE
Usefulness of content-type in secrets

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/oo7#133]
Currently, the secrets have a content-type field that I don't really see what it is useful for. especially that it is specific to the dbus implementation, making the generic API not cover it.

If you look for it usages inside oo7, you will find various `text/plain` and some probably mistakes of `text/utf8` (proves that we don't really make use of it).

gnome-keyring also doesn't make use of it and always sets it to `text/plain`, see https://gitlab.gnome.org/GNOME/gnome-keyring/-/blob/master/daemon/dbus/gkd-secret-secret.c

kwallet on the other hand, seems to only care if it is a text or a binary blob at https://github.com/KDE/kwallet/blob/28a47505b5ecfa9269fa34e8ede5ea63c041f374/src/runtime/kwalletd/kwalletfreedesktopcollection.cpp#L184

So I am considering removing that API completely and keep it an implementation detail. Replacing the usual API that takes `secret: impl AsRef<[u8]>, content_type: &str` with an enum like

```rust
pub enum Secret {
   Text(String),
   Blob(Vec<u8>)
}
```

Which will automatically set the correct content-type.

cc @ueno @A6GibKm

**Comment by A6GibKm** [comment]
I would like to know if there are more well-known content types other than `text/plain`.

**Comment by bilelmoussaoui** [comment]
Even if an app would set one, the most popular server side implementation completely ignore them.

Having it as an enum means we can extend it in the future without making it error prone.
