### ISSUE TITLE
Implement locking and unlocking items

### ISSUE THREAD

**Issue by Schmiddiii** [bilelmoussaoui/oo7#39]
Currently, the general `oo7::Item` has no `lock`, `unlock` and `is_locked` methods like the `oo7::dbus::Item` has. This can cause issues when the generic `oo7::Item` is used, the backend uses dbus and the queried item is locked.

Related downstream issue: https://gitlab.com/Schmiddiii/flare/-/issues/88

**Comment by bilelmoussaoui** [comment]
Should be part of 0.2 that I just released

**Comment by WhyNotHugo** [comment]
Thanks!
