### ISSUE TITLE
Rekeying support for oo7::portal::Keyring

### ISSUE THREAD

**Issue by ueno** [bilelmoussaoui/oo7#47]
The [oo7](https://docs.rs/oo7/latest/oo7/index.html)::[portal](https://docs.rs/oo7/latest/oo7/portal/index.html)::[Keyring](https://docs.rs/oo7/latest/oo7/portal/struct.Keyring.html#) API currently doesn't provide a way to change the key. It would be nice if there is an API, something like:
```rust
pub async fn change_secret(&mut self, secret: Secret) -> Result<(), Error>;
...
let mut keyring = oo7::portal::Keyring::load_path(..., secret).await?;
keyring.change_secret(new_secret).await?;
keyring.write().await?;
```
This would be particularly useful for implementing a gnome-keyring compatible server backed by this file format (#46) and supporting password change through PAM.

**Comment by sophie-h** [comment]
> The [oo7](https://docs.rs/oo7/latest/oo7/index.html)::[portal](https://docs.rs/oo7/latest/oo7/portal/index.html)::[Keyring](https://docs.rs/oo7/latest/oo7/portal/struct.Keyring.html#) API currently doesn't provide a way to change the key

You can use [`replace_item_index()`](https://docs.rs/oo7/latest/oo7/portal/struct.Keyring.html#method.replace_item_index) for that already.

> It would be nice if there is an API, something like

This would need some rework of how the library works right now. Currently the `portal::Item` does not know anything about the keyring file.

**Comment by ueno** [comment]
I think there is a confusion; this issue is about master password to encrypt the items, not the items themselves.

**Comment by sophie-h** [comment]
Oh sorry, I was totally off.

**Comment by warusadura** [comment]
@bilelmoussaoui I'm interested in working on this issue as well :)
