### ISSUE TITLE
Connecting to SecretService signals

### ISSUE THREAD

**Issue by sophie-h** [bilelmoussaoui/oo7#57]
I would like to connect to secret service signals. With what we have the naive implementation would probably look like

```
    pub async fn receive_item_changed(
        &self,
    ) -> Result<impl futures_util::Stream<Item = Item<'_>>, Error> {
        self.inner.receive_item_changed().await.map(|stream| {
            stream.map(|item| {
                Item::new(
                    Arc::clone(&self.service),
                    Arc::clone(&self.session),
                    self.algorithm,
                    item,
                    self.aes_key.as_ref().map(Arc::clone),
                )
            })
        })
    }
```

However, oo7 only deals with `Item<'static>` which we don't get here. I think it's a zbus limitation at the moment.

To work around this, I would like to add `Collection::item_for_path` and `Item::path` functions, since together they would allow us to get a static version of the item.

Any thoughts? Otherwise, I would implement this.

**Comment by bilelmoussaoui** [comment]
> However, oo7 only deals with Item<'static> which we don't get here. I think it's a zbus limitation at the moment.

What do you mean by oo7 only dealing with `Item<'static>`? 

> To work around this, I would like to add Collection::item_for_path

What would such function do?

> and Item::path functions

I would implement `Deref` for `zbus::Proxy` on all the `dbus::api` types.

**Comment by sophie-h** [comment]
Found the lifetime issue in the existing code. Tried to add all explanations to the commit messages.
