### ISSUE TITLE
cli: Do not assume secrets are valid utf8

### ISSUE THREAD

**Issue by A6GibKm** [bilelmoussaoui/oo7#65]
Portal secrets are random bytes, hence the cli will crash.

We should load them into a OsString and have a --hex flag to display them as hex.

**Comment by sophie-h** [comment]
OsString sounds wrong. On Windows, for example, an OSString has to be valid utf16, right? Binary data is just binary data.

**Comment by A6GibKm** [comment]
But this is a linux app which could be piped into something else

**Comment by bilelmoussaoui** [comment]
![image](https://github.com/bilelmoussaoui/oo7/assets/7660997/763f56b1-e326-4eec-9e91-01908c621959)
i agree, this is not great (both cases)
