### ISSUE TITLE
oo7::portal::Keyring::items() is no longer async anymore since 0.3

### ISSUE THREAD

**Issue by haecker-felix** [bilelmoussaoui/oo7#80]
Despite being `async` it is currently blocking. Affected function seems to be `derive_key()`

![image](https://github.com/bilelmoussaoui/oo7/assets/6001248/e982c89f-8ef5-4de6-949b-7e12d19004f1)

May be related 
- https://github.com/bilelmoussaoui/oo7/pull/77
- https://github.com/bilelmoussaoui/oo7/commit/86c2a8f41bece33882358c795f0f06111329be95

**Comment by sophie-h** [comment]
I think I already mentioned before that I added the `spawn_blocking` for a reason and it cannot just be removed.

**Comment by bilelmoussaoui** [comment]
> I think I already mentioned before that I added the `spawn_blocking` for a reason and it cannot just be removed.

I haven't received any review about it. I even pinged you on github but I do understand the overwhelming amount of notifications... so not an issue.

I rather make https://github.com/bilelmoussaoui/oo7/blob/main/client/src/portal/api/mod.rs#L247 do the spawn_blocking bit instead.
