### ISSUE TITLE
Unable to change secret of dbus item

### ISSUE THREAD

**Issue by haecker-felix** [bilelmoussaoui/oo7#93]
Using `oo7::dbus::Item::set_secret()`

```
Could not change secret: service error org.freedesktop.zbus.Error: Type of message, “(oayays)”, does not match expected type “((oayays))”
```

oo7 v0.3.2

**Comment by bilelmoussaoui** [comment]
This might be a zbus regression. I would suggest writing a new test case, run it against main and then against some old oo7 release like 0.1/0.2 and see if it still happens. The signature is correct, at worst we can work around it by adding an extra tuple when serializing the secret for SetSecret calls

**Comment by bilelmoussaoui** [comment]
Might be related to https://github.com/bilelmoussaoui/ashpd/commit/5cf31e35aed98236f47e86b0bf520a44d6c6242a
